Module structure_definition
    Public Structure job
        Dim job_id As Integer 'PK - Autogenerated
        <VBFixedString(16)> Dim job_username As String 'Automatically generated from PC name
        <VBFixedString(16)> Dim job_date_created As String 'Automatically generated
        <VBFixedString(16)> Dim job_name As String 'Textbox input
        Dim job_pinned As Boolean 'checkbox
        Dim job_count As Integer 'autogenerated
    End Structure
    Public Structure job_product
        Dim job_id As Integer 'FK - Automatically generated
        Dim product_id As Integer 'FK - Automatically generated
        Dim quantity As Integer 'Combobox
    End Structure
    Public Structure product
        Dim product_id As Integer 'PK 'Automatically generated
        <VBFixedString(16)> Dim product_desc As String 'Input via Texbox
        <VBFixedString(16)> Dim product_ass_location As String 'Input Via Combo box
    End Structure
    Public Structure product_component
        Dim product_id As Integer 'FK 'Automatically generated
        Dim component_id As Integer 'FK 'Automatically generated
        Dim quantity As Integer ' Combo box
    End Structure
    Public Structure component
        Dim component_id As Integer 'PK 'Automatically generated
        <VBFixedString(16)> Dim component_desc As String 'Textbox Input
    End Structure
    Public Structure component_location
        Dim component_id As Integer 'FK 'Automatically generated
        Dim location_id As Integer 'FK 'Automatically generated
        Dim stock_count As Integer 'Combo box
    End Structure
    Public Structure location
        Dim location_id As Integer 'PK 'Automatically generated
        <VBFixedString(16)> Dim location_desc As String 'TextBox Input
        '<VBFixedString(16)> Dim location_contents As String 'TextBox Input
    End Structure
    Public job_record As job
    Public location_record As location
    Public component_record As component
    Public product_record As product
End Module
